version: "3"

services:
    joomla:
        image: joomla:fpm
        links:
            - joomladb:mysql
        ports:
            - 9000
        environment:
          JOOMLA_DB_HOST: joomladb
          JOOMLA_DB_PASSWORD: example
        volumes:
          - joomlavol:/var/www/html

    joomladb:
        image: mysql:5.6
        environment:
            MYSQL_ROOT_PASSWORD: example
        volumes:
          - ./mysqldb:/var/lib/mysql/
    nginx:
        image: nginx
        ports:
          - 8081:8081
        depends_on:
          - joomla
        volumes:
          - joomlavol:/var/www/html
          - ./default.conf:/etc/nginx/conf.d/default.conf
    front-nginx:
        image: nginx
        ports:
          - 80:80
        depends_on:
          - nginx
        volumes:
          - ./front-nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  joomlavol:
